### PR TITLE
RPSLS_other version_if statement

### PR DESCRIPTION
**Pull request by n-tammy**
Hello!

This is my suggestion on the  RPSLS project. I'd be very happy to get any feedback, if it's too long for example, and if you have any spare time, a tip on how to improve it.

Thank you in advance!

### CODE REVIEW

**Comment by sonnynomnom** [comment]
hi @n-tammy this looks great! two things:

1. can you change the name of the file you are adding from **RPSLS_if** to **RPSLS_if.cpp**?
2. what's your codecademy username?

**Comment by n-tammy** [comment]
Hello!

Thank you so much for your feedback! I changed the name of the file and
also, my codecademy username is n.tammy(very innovative, I know).

Thank you again so much!

Στις Δευ, 3 Ιουν 2019 στις 8:58 μ.μ., ο/η Sonny Li <notifications@github.com>
έγραψε:

**Comment by sonnynomnom** [comment]
woohoo!

**Comment by n-tammy** [comment]
Thank you so much! And thank you for the correction :)

Στις Τρί, 4 Ιουν 2019 στις 11:46 μ.μ., ο/η Sonny Li <
notifications@github.com> έγραψε:

**Pull request merged**
